apiVersion: v1
kind: Pod
metadata:
  name: aplicativo
  labels:
    app: aplicativo
spec:
  hostNetwork: false
  hostIPC: false
  hostPID: false
  containers:
  - name: ubuntu-container
    image: nginx
    command: ["sleep", "infinity"]
    securityContext:
      privileged: false
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
  restartPolicy: Never
