name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image
        run: |
          docker pull vulnerables/web-dvwa:latest
          docker images

      - name: Download Artifact Scanner
        run: |
          wget https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
          tar -xzvf tmas-cli_Linux_x86_64.tar.gz
  
      - name: Image Scanning
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: |
          # ./tmas scan docker:vulnerables/web-dvwa:latest -VMS --saveSBOM > results.json  --override overrides.yml
          ./tmas scan docker:vulnerables/web-dvwa@sha256:dae203fe11646a86937bf04db0079adef295f426da68a92b40e3b181f337daa7 -VMS --saveSBOM > results.json  --override overrides.yml
  
  
      - name: Upload Json as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-json
          path: results.json  
  
  
      - name: Checking Vulnerabilities Scan Results
        run: |
          cat results.json | jq '.vulnerabilities | { totalVulnCount, criticalCount, highCount, mediumCount, lowCount, negligibleCount, unknownCount } | to_entries | .[] | "\(.key): \(.value)"'
          cat results.json | jq '.vulnerabilities.criticalCount < 316 and .vulnerability.highCount < 761 and .vulnerability.mediumCount < 701' | grep -q false && { echo "No se cumple con los criterios de vulnerabilidades. Deteniendo el pipeline."; exit 1; } || echo "Se cumple con los criterios de vulnerabilidades. Continuando con el pipeline."
          
